# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "home"
#   url = "#about"
#   weight = 10

[[main]]
  name = "about me"
  url = "/about"
  weight = 10

[[main]]
  name = "projects"
  url = "#projects"
  weight = 20

[[main]]
  name = "papers"
  url = "#papers"
  weight = 30

[[main]]
  name = "travel"
  url = "/travel"
  weight = 40 

[[main]]
  name = "blog <i class='fas fa-external-link-alt' style='opacity:0.3'></i>"
  url = "https://medium.com/@benjixie"
  # url = "#blog"
  weight = 50

[[main]]
  name = "cv"
  url = "/files/cv.pdf"
  weight = 60

# [[main]]
#   name = "Impact"
#   url = "#impact"
#   weight = 60  

# [[main]]
#   name = "Bio"
#   url = "#bio"
#   weight = 80

[[main]]
  name = "contact"
  url = "#contact"
  weight = 100

# [[main]]
#   name = "HIRE ME!"
#   url = "/hireme"
#   weight = 110